### ISSUE TITLE
BUG: Creating a receipt does nothing

### ISSUE THREAD

**Issue by Adventurousdonut** [mikygee/immobilier#4]
![grafik](https://user-images.githubusercontent.com/110562645/183464487-1dba87a9-28e9-42a3-b48f-d97a7dab9b1c.png)

After creating a new receipt and pressing "Create" once all the data has been put it in creates a blank page like shown above.

**Comment by mikygee** [comment]
The white page is probably because you don't display PHP errors.
I have an error too.
I don't remember what I did to create receipts, I think one field is messing up.

**Comment by mikygee** [comment]
Hello,

So in one case I'm able to create a receipt, it's when I have a thirdparty configured
![image](https://user-images.githubusercontent.com/2222550/183528340-e272caa1-8d88-47bc-8b80-1361d1feb198.png)

I should have found out quicker because the error message
`Fatal error: Uncaught Error: Call to a member function getNomUrl() on null in /.../htdocs/ultimateimmo/receipt/immoreceipt_card.php:992 Stack trace: #0 {main} thrown in /.../htdocs/ultimateimmo/receipt/immoreceipt_card.php on line 992`
leads me to line 992
`$morehtmlref .= '<br>' . $langs->trans('ThirdParty') . ' : ' . $object->thirdparty->getNomUrl(1, 'renter');`
and there we do see the word thirdparty

Coming back to the error message we see that it complains about something being null

Probably a if statement should be added before this line.

**Comment by Adventurousdonut** [comment]
Hey,

Oh i didn't try that. Thanks for finding the bug!

**Comment by mikygee** [comment]
I close this issue here, I have opened this one
https://github.com/Darkjeff/immobilier/issues/83
